services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:ollama
    ports: [3000:8080]
    volumes:
      - open-webui:/app/backend/data
      - ollama:/root/.ollama
    restart: on-failure:3

volumes:
  open-webui:
  ollama:
