volumes:
  open-webui:
  ollama:

services:
  ollama:
    container_name: ollama
    image: ollama/ollama
    ports:
      - '11434:11434'
    volumes:
      - /mnt/md5/config/ollama:/root/.ollama
    
  open-webui:
    container_name: ai
    image: ghcr.io/open-webui/open-webui:ollama
    ports:
      - '3000:8080'
    volumes:
      - /mnt/md5/config/open-webui:/app/backend/data
    environment:
      OLLAMA_BASE_URL: http://localhost:11434
    restart: unless-stopped

  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ='America/Los_Angeles'
      - VERSION=docker
    volumes:
      - /mnt/md5/config/plex:/config
      - /mnt/md5/television:/tv
      - /mnt/md5/movies:/movies
      - /mnt/md5/music:/music
    restart: unless-stopped

  # More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    dns:
      - 8.8.8.8
      - 8.8.4.4
    volumes:
      # For persisting Pi-hole's databases and common configuration file
      - /mnt/md5/config/pihole:/etc/pihole
    cap_add:
      # See https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
      # Required if you are using Pi-hole as your DHCP server, else not needed
      - NET_ADMIN
      # Required if you are using Pi-hole as your NTP client to be able to set the host's system time
      - SYS_TIME
      # Optional, if Pi-hole should get some more processing time
      - SYS_NICE
    ports:
      # DNS Ports
      - "53:53/tcp"
      - "53:53/udp"
      # Default HTTP Port
      - "8080:80/tcp"
      # Default HTTPs Port. FTL will generate a self-signed certificate
      - "8443:443/tcp"
      # Uncomment the below if using Pi-hole as your DHCP Server
      #- "67:67/udp"
      # Uncomment the line below if you are using Pi-hole as your NTP server
      #- "123:123/udp"
    environment:
      # Set the appropriate timezone for your location from
      # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones, e.g:
      TZ: 'America/Los_Angeles'
      # Set a password to access the web interface.
      # Not setting one will result in a random password being assigned
      FTLCONF_webserver_api_password: 'changeme'
      # If using Docker's default `bridge` network setting the dns listening mode should be set to 'all'
      FTLCONF_dns_listeningMode: 'all'
    restart: unless-stopped
