- name: Configure apt
  ansible.builtin.apt:
    autoclean: "{{ _apt_autoclean }}"
    autoremove: "{{ _apt_autoremove }}"
  become: true

- name: Configure apt packages
  ansible.builtin.apt:
    name: "{{ apt }}"
  become: true

- name: Configure pip packages
  ansible.builtin.pip:
    name: "{{ pip }}"
    virtualenv: "{{ virtualenv_path }}"
    virtualenv_command: python3 -m venv
